### ISSUE TITLE
OverflowException - Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by caunt** [L3tum/HardwareInformation#19]
Hi! When building in "Any CPU" mode everything works fine, but after change to "x86" i get an error:

System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(Int64 value)
   at HardwareInformation.ThreadAffinity.Set(UInt64 mask)
   at HardwareInformation.Util.<>c__DisplayClass5_0.<RunAffinity>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by L3tum** [comment]
Hi, sorry about the late reply.

The library currently assumes a 64-Bit Processor and OS and thus uses 64-Bit Integers for certain operations. I'm not sure how well I could support 32-bit systems, but I'll try to add support for it.

**Comment by caunt** [comment]
It would be nice if you can at least wrap that code in try { } catch { } block. As i understand most of other code can should work properly on x86 machines.

We appreciate your help. Thank you anyway 👍 Your library help us collect a lot of information from our users.

**Comment by L3tum** [comment]
Should be fixed in eda5612 if you can give it a try. Didn't know about IntPtr being platform-specific honestly, good to know.

**Comment by caunt** [comment]
Okay 👍 
Would be great upload an update to nuget. We will test update on our users in days.

**Comment by L3tum** [comment]
Should be published as 4.0.1 now. Let me know if you run into any issues

**Comment by caunt** [comment]
Today we released internal update with 4.0.1 version to our users. Waiting for results 😄

**Comment by caunt** [comment]
👍 now seems to be working but also we see some exceptions from AppDomain.CurrentDomain.FirstChanceException event handler: 
![image](https://user-images.githubusercontent.com/5324218/96960341-dc036b80-150a-11eb-8502-0a7f5913a98b.png)

**Comment by L3tum** [comment]
Hmmm, can you confirm that your 32-Bit Application isn't run on a 64-Bit OS? Unfortunately, it seems like .NET isn't smart enough to allow this, so it breaks if 32-Bit Applications are run on 64-Bit Operating systems. The exception doesn't cause any harm since it's caught anyway.

**Comment by caunt** [comment]
😟 Yes we are running 32-Bit app on 64-Bit OS. Our application does not require any architecture-specific behavior, so we are publishing release for win-x86 platform which can be run on both OS Architectures.

**Comment by caunt** [comment]
I've found that you can use Environment.Is64BitOperatingSystem which will gracefully detect OS Architecture regardless is app compiled for 32-Bit architecture or not (https://stackoverflow.com/a/336729/11815290)

**Comment by L3tum** [comment]
Ah, that's a problem then. I don't really see a way to fix this unfortunately, since for .NET, `IntPtr` assumes the platform-bitness (i.e. 32-Bit or 64-Bit) while .NET expects the Process-Bitness (i.e. X86 (32-bit) or X64 (64-bit)). 

Then the problem is that the platform integer (i.e. 64-bit) is cast to the process integer (i.e. 32-bit) and causes an OverflowException. 

I've already tested it out with the Environment configuration but it doesn't seem to work. 

I'll try to find a workaround, though no promises

**Comment by caunt** [comment]
What do you think about Environment.Is64BitProcess? (**not** Is64BitOperatingSystem propert)

**Comment by L3tum** [comment]
Tried that out and it seems in conjunction with switching to int (rather than uint that you'd expect), it seems to work now. Published as 4.0.3. Please test it out and let me know if you run into any issues :)

**Comment by caunt** [comment]
Seems to be fixed 👍

**Comment by L3tum** [comment]
Cool, thanks for testing it out. This is definitely going into my "bugs I'd never thought I'd have" list.
